classDiagram
    namespace sample {
        class B {
            +void doSomething()
        }
        class A
        class C
    }
    namespace dummy {
        class E {
            +String publicField
            +String getPublicField()
            +String greet(String)
        }
        class D {
            +String greet(String)
        }
    }
    sample.A ..> sample.B
    dummy.D <|.. dummy.E
    dummy.E ..> dummy.D
    sample.A <|-- sample.C
    sample.C ..> sample.B
    sample.C ..> sample.A
