classDiagram
    class com.example.sample.B
    class com.example.sample.A
    com.example.sample.A ..> com.example.sample.B
    class com.example.sample.D
    class com.example.sample.C
    com.example.sample.A <|-- com.example.sample.C
    com.example.sample.C ..> com.example.sample.B
    com.example.sample.C ..> com.example.sample.A
    class com.example.sample.E
    com.example.sample.D <|.. com.example.sample.E
    com.example.sample.E ..> com.example.sample.D
