@startuml
class com.example.sample.B {
    + void doSomething()
}
class com.example.sample.A {
}
com.example.sample.A ..> com.example.sample.B
class com.example.dummy.E {
    + String publicField
    + String getPublicField()
    + String greet(String)
}
com.example.dummy.D <|.. com.example.dummy.E
com.example.dummy.E ..> com.example.dummy.D
class com.example.dummy.D {
    + String greet(String)
}
class com.example.sample.C {
}
com.example.sample.A <|-- com.example.sample.C
com.example.sample.C ..> com.example.sample.B
com.example.sample.C ..> com.example.sample.A
@enduml
